persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Port Ayarları
listener 1883
allow_anonymous true

# Web Socket Desteği (Frontend doğrudan bağlanmak isterse)
listener 9001
protocol websockets
allow_anonymous true
