"""add_cascade_delete_to_port_station

Revision ID: 398257ace9b1
Revises: 20260506_0005
Create Date: 2026-05-11 11:00:40.179630
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '398257ace9b1'
down_revision = '20260506_0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_stations_port_id_ports'), 'stations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_stations_port_id_ports'), 'stations', 'ports', ['port_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_stations_port_id_ports'), 'stations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_stations_port_id_ports'), 'stations', 'ports', ['port_id'], ['id'])
    # ### end Alembic commands ###
